### ISSUE TITLE
Issue with RaMP when performing Pathway Enrichment

### ISSUE THREAD

**Issue by KDSpencer77** [ncats/RaMP-DB#3] opened 2020-05-29 00:33 UTC
I am trying to return pathways from given analytes by using a batch query for multiple analytes on the server hosted by NCATS at https://rampdb.ncats.io. When I paste the list of analytes and hit submit query everything appears to be fine. When I hit run pathway analyses the following error in the attached screenshot occurs. I have also provided an Excel file with the list of analytes (one on each row). Any help would be greatly appreciated.

[Analytes_for_GitHub_Issue.xlsx](https://github.com/ncats/RaMP-DB/files/4698997/Analytes_for_GitHub_Issue.xlsx)
<img width="465" alt="Screen Shot 2020-05-28 at 8 33 22 PM" src="https://user-images.githubusercontent.com/42778475/83207991-82953d00-a122-11ea-8b3c-c2f132386cc9.png">

**Comment by Mathelab** [comment] 2020-05-29 01:34
From Garrett: That error message (https://datatables.net/manual/tech-notes/4) seems to be coming from the javascript.  Looks like shiny is producing a table with a missing element somewhere.
I'd check to make sure row 44 column 1 of the requested table doesn't have an NA or something weird in it

**Comment by johnbraisted** [comment] 2020-05-29 23:39
The patch has been committed. The creation of the rendered DataTable in two files lacked 'DT::' like other table creation functions. I think the issue is that our server and my local testing environment use the latest shiny v1.4.0.2. I'll keep this case open until our IT applications folks put this to the server.

**Closed** 2020-06-01 15:52 UTC
Labels: bug
